version: 1.0.{build}
branches:
  only:
  - master
  - hexin
image: Visual Studio 2019
configuration: release
platform: x64
environment:
  PYTHON: C:/Python37-x64
  PATH: C:/OneFLOW/bin;"C:/Program Files/CMake/bin/";C:/Program Files/Microsoft MPI/Bin;%PATH%
build_script:
- ps: >-
    powershell ci/appveyor/oneflow_windows_actions.ps1
test_script:
- cmd: >-
    cd test
    
    %PYTHON%/python.exe test.py "mpiexec -n 1" "OneFLOW"
    
    ECHO %PATH%